### ISSUE TITLE
Error on mandatory config file:  toml: cannot load TOML value of type int64 into a Go float

### ISSUE THREAD

**Issue by leopku** [yvesago/glauth-ui-light#4]
First run glauth-ui-light with `./glauth-ui-app -c glauth-ui-light.conf`

OS          -  macOS 11.6.5 Big Sur
CPU         -  Intel® Core™ i7-9750H CPU @ 2.60GHz (12)
Memory      -  7.7 GB/16.8 GB
glauth-ui-app v1.4.2, git: 4541f2d, build: 2022-06-20T13:10:25+0800

```toml
#######################
# glauth-ui-light.conf

# dbfile: glauth conf file
#    with watchconfig enabled for hot-reload on conf file change
#    glauth-ui-light need write access
dbfile = "samples-conf/glauth-sample-simple.cfg"

# run on a non privileged port
port = "0.0.0.0:8080"
# When a self hosted ssl reverse proxy is used :
#  port = "127.0.0.1:8080"

# Custom first page texts
appname = "glauth-ui-light"
appdesc = "Manage users and groups for glauth ldap server"

[sec]
  # TODO set random secrets for CSRF token
  csrfrandom = "secret1"

[passpolicy]
  min = 2
  max = 24
  allowreadssha256 = true  # to be set to false when all passwords are bcrypt
  entropy = 60             # optional password constraint


[cfgusers]
  start = 5000           # start with this uid number
  gidadmin = 5501        # members of this group are admins
  gidcanchgpass = 5500   # members of this group can change their password
  giduseotp = 5501       # members of this group use OTP

[cfggroups]
  start = 5500   # start with this gid number
```
